spring:
  cloud:
    inetutils:
      preferred-networks: 172.20.10.4
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
