spring:
  application:
    name: test
server:
  port: 9999
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123@localhost:8100/eureka/
data:
  message: '{cipher}AQCjH14DBCr7kNwA6W8Zy3AbJT8V6MZiVsV4TmuLAVKbtK+dXfRx8i8rqvvW2G+HeInfvowzYAHCO89Rie3jDKbgw/CSSRBl+lk1IOmSxdpJxl+3vUeAkj7gynEXr9nfGbDimSjQdAERgftAb+WpqrTO/IAZGJDzi635DyEdacZmEbLwXQSHrkcAqi8rCiX4tcYSoPg/ekLZR9+5j3LGPCyaTA0UCJnP8b3Hhs9C1+svJKTPr9hH7JwN8mW2Fx3yBK9SyZ9o3BoOZPbg67/VsaA01/CPRjQBWlUysJPdw0s2Msm2LMGQaTmOo5sxEn2WylMVJ9o0fECwi628+eooRpkfSzbg3bRYEFwiDV+FOH2AGvC8KKZKATJGwpO+hIVDGeE='
