spring:
  application:
    name: register
  security:
    user:
      name: admin
      password: admin123
  profiles:
    # 当前启动的节点配置名
    active: node2
  cloud:
    inetutils:
      preferred-networks: 10.205.29.42
eureka:
  instance:
    prefer-ip-address: true
  server:
     enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
